@startuml

left to right direction



actor Administrador as "Administrador"
actor SistemaExterno as "Sistema Financiero"


rectangle "Crear Usuario" {
  Administrador --> (Crear Usuario)
  
  (Crear Usuario) ..> (Verificar Validez del Usuario) : <<include>>
  (Verificar Validez del Usuario) <-- SistemaExterno


  
  (Validar Datos Ingresados) <.right. (Verificar Validez del Usuario) : <<include>>
  
  (Validar Datos Ingresados) <.up. (Crear Registro de Usuario) : <<extend>>
  (Validar Datos Ingresados) <.left. (Mostrar Mensaje de error) : <<extend>>
  
  (Mostrar Mensaje de exito) <.left. (Crear Registro de Usuario): <<include>>
  
  note bottom of (Verificar Validez del Usuario)
    Se verifica que el usuario este
    habilitado en el sistema financiero
  end note


}

@enduml
