@startuml

node "Usuario" as user {
    component "Interfaz de Usuario" as UI
    component "Aplicacion Web" as WebApp
}

node "Servidor Backend" as web_server {
    component "BL" as Backend
    component "Spring Boot" as SpringBoot
    ' component "Java" as Java
    component "Autenticacion" as Auth

}

node "Servidor de Autenticación" as Auth_Server {

    component "Keycloak" as AuthService

}

node "Sistema Financiero Privado" as Financial_Server {
    component "Sistema Financiero" as FinancialSystem
}

node "Base de Datos" as BD {
    component "PostgreSQL" as Database
}

UI <--> SpringBoot
Backend --> Database
Auth --> AuthService
Backend --> FinancialSystem

@enduml
